[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_ENDPOINT = "https://location-api-backend.onrender.com/api/location"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 